import json
import re
from pathlib import Path
from typing import Dict, List
from urllib.parse import urlparse

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .config import CaptureConfig
from .logging_utils import local_now, read_json, utc_now, write_json
from .manifest import summarize_run


def template_environment() -> Environment:
    template_root = Path(__file__).resolve().parents[2] / "templates" / "reports"
    return Environment(loader=FileSystemLoader(str(template_root)), autoescape=select_autoescape(enabled_extensions=()))


def anomaly_lines(validation: Dict[str, object]) -> List[str]:
    lines = []
    for retry in validation.get("render_retries", []):
        lines.append(f"- Render retry for `{retry.get('url')}`; resolved: `{retry.get('resolved')}`.")
    for warning in validation.get("warnings", []):
        lines.append(f"- Warning: `{warning}`.")
    if not lines:
        lines.append("- No anomalies or retries recorded.")
    return lines


def write_readme(path: Path, title: str, body: str) -> None:
    path.mkdir(parents=True, exist_ok=True)
    (path / "README.md").write_text(f"# {title}\n\n{body.strip()}\n", encoding="utf-8")


def site_slug(target_url: str, fallback: str) -> str:
    host = urlparse(target_url).netloc.lower() or fallback
    return re.sub(r"[^a-z0-9.-]+", "-", host).strip("-") or fallback


def write_start_here(config: CaptureConfig, run_dir: Path, validation_status: str) -> None:
    site = site_slug(config.target_url, config.case_slug)
    run_stamp = run_dir.name
    full_zip = f"{site}-{run_stamp}.zip"
    browse_zip = f"{site}-{run_stamp}-website-html.zip"
    text = f"""# Start Here

This snapshot preserves a public website capture for:

`{config.target_url}`

Run folder:

`{run_stamp}`

Validation status:

`{validation_status}`

## What To Open First

1. Open `report/report.md` to read the complete technical report.
2. Open `manifest/evidence-summary.json` for the short machine-readable summary.
3. Open `validation/validation.json` to see validation checks, warnings, failures, and retry records.
4. Open `hashes/files.sha256` to verify file integrity.

## Browse The Captured Website Locally

Use this smaller ZIP when you only want to navigate the captured HTML pages:

`{browse_zip}`

Download it, unzip it, then open:

`open-rendered-mirror.html`

If that file does not show useful content, open:

`open-static-mirror.html`

For self-contained individual page exports, open:

`singlefile-index.html`

The rendered mirror reflects browser-observed HTML from the workflow runner. The static mirror reflects public HTTP HTML with executable scripts disabled for offline review.

## Download The Complete Snapshot

Use this ZIP when you want the entire evidence package:

`{full_zip}`

It contains the report, manifests, validation, hashes, logs, WARC/WACZ files, screenshots, PDFs, HTML mirrors, SingleFile outputs when available, and browser/network evidence.

## Folder Guide

- `report/`: human-readable report files.
- `manifest/`: structured JSON records.
- `validation/`: validation result files.
- `hashes/`: SHA-256 integrity hashes.
- `logs/`: tool logs and workflow logs.
- `artifacts/`: captured website evidence.

This is technical preservation support, not legal advice. Captured material can include copyrighted content, personal data, tracking metadata, or third-party content.
"""
    (run_dir / "START-HERE.md").write_text(text, encoding="utf-8")


def write_tool_log_summary(run_dir: Path) -> None:
    log_root = run_dir / "logs"
    log_root.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Tool Log Summary",
        "",
        "This file indexes structured logs generated by the evidence capture tool.",
        "The raw log files remain preserved in this folder as JSON Lines where possible.",
        "",
        "| Log file | Events | First timestamp | Last timestamp | Errors | Messages |",
        "| --- | ---: | --- | --- | ---: | --- |",
    ]
    for log_path in sorted(log_root.glob("*.log")):
        events = []
        errors = 0
        messages = []
        for raw_line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
            if not raw_line.strip():
                continue
            try:
                event = json.loads(raw_line)
            except json.JSONDecodeError:
                event = {"message": raw_line}
            events.append(event)
            if event.get("error"):
                errors += 1
            message = str(event.get("message", "")).strip()
            if message and message not in messages:
                messages.append(message)
        first = ""
        last = ""
        timestamps = [
            str(event.get("timestamp_utc") or event.get("timestamp_local") or "")
            for event in events
            if event.get("timestamp_utc") or event.get("timestamp_local")
        ]
        if timestamps:
            first = timestamps[0]
            last = timestamps[-1]
        message_text = ", ".join(messages[:6])
        if len(messages) > 6:
            message_text += f", and {len(messages) - 6} more"
        lines.append(
            f"| `{log_path.name}` | {len(events)} | `{first}` | `{last}` | {errors} | {message_text or 'n/a'} |"
        )
    if len(lines) == 8:
        lines.append("| n/a | 0 |  |  | 0 | No tool logs found. |")
    lines.extend(
        [
            "",
            "Forensic value: these logs preserve the sequence of tool operations, selected URLs, status values, retry outcomes, warnings, and errors observed during the run.",
        ]
    )
    (log_root / "tool-log-summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_snapshot_readmes(config: CaptureConfig, run_dir: Path, context: Dict[str, object]) -> None:
    summary = context["summary"]
    validation = context["validation"]
    generated = context["generated_utc"]
    site = site_slug(config.target_url, config.case_slug)
    run_stamp = run_dir.name
    full_zip = f"{site}-{run_stamp}.zip"
    browse_zip = f"{site}-{run_stamp}-website-html.zip"
    common = (
        f"Target URL: `{config.target_url}`\n\n"
        f"Case slug: `{config.case_slug}`\n\n"
        f"Run directory: `{run_dir.name}`\n\n"
        f"Generated UTC: `{generated}`\n\n"
        f"Validation status: `{summary.get('validation_status')}`\n\n"
        "This package is technical preservation support, not legal advice. "
        "It preserves public website evidence collected by an automated, source-available workflow. "
        "Repository visibility controls who can inspect the source, workflow definition, and committed outputs."
    )
    write_readme(
        run_dir,
        "Snapshot Overview",
        common
        + "\n\n"
        "Start with `START-HERE.md` for simple download and opening instructions. "
        "Then read `report/report.md`. Review `manifest/validation.json`, "
        "`hashes/files.sha256`, and `logs/` for technical traceability. "
        f"Use `{browse_zip}` to browse the captured HTML locally. "
        f"Use `{full_zip}` to download the complete snapshot. "
        "The `artifacts/` tree contains the preserved website outputs."
        + "\n\n"
        "Forensic value: this directory ties the target scope, collection method, timestamps, "
        "tool metadata, generated artifacts, hashes, validation checks, and logs into one reviewable record. "
        "It does not guarantee legal admissibility; admissibility depends on jurisdiction, process, and expert review."
    )
    write_readme(
        run_dir / "report",
        "Reports",
        "Human-readable reports summarizing what was captured, how it was captured, "
        "integrity checks, limitations, privacy/network observations, and anomalies/retries. "
        "Use `report.md` as the combined report.\n\nForensic value: reports provide a reviewer-friendly explanation "
        "of technical evidence without replacing the raw artifacts, manifests, hashes, and logs."
    )
    write_readme(
        run_dir / "manifest",
        "Manifests",
        "Structured JSON records for configuration, URL inventory, capture results, render results, "
        "WARC/WACZ packaging, validation, evidence summary, and package metadata.\n\n"
        "Forensic value: manifests provide machine-readable facts that can be independently checked "
        "against artifacts and logs."
    )
    write_readme(
        run_dir / "validation",
        "Validation",
        "Validation output produced after capture and packaging. It records pass/fail/warning status, "
        "mirror-content checks, WARC/WACZ checks, render artifact checks, retries, and sensitive-pattern scan results.\n\n"
        f"Current validation failures: `{validation.get('failures', [])}`\n\n"
        f"Current validation warnings: `{validation.get('warnings', [])}`"
    )
    write_readme(
        run_dir / "hashes",
        "Hashes",
        "SHA-256 hashes for produced files, excluding generated hash lists and file manifests from their own calculation.\n\n"
        "Forensic value: hashes allow later integrity checks to detect file changes after capture."
    )
    write_readme(
        run_dir / "logs",
        "Logs",
        "Structured logs from each tool step, plus GitHub Actions workflow logs when available. "
        "Logs use JSON Lines where possible so they can be searched, parsed, and compared. "
        "Start with `tool-log-summary.md` for an index of local tool logs.\n\n"
        "Forensic value: logs show the operational sequence, timestamps, selected URLs, retries, warnings, "
        "and tool behavior during collection."
    )
    write_readme(
        run_dir / "logs" / "github-actions",
        "GitHub Actions Logs",
        "Workflow metadata, job metadata, and text logs captured from the GitHub Actions run when available. "
        "GitHub may delete native Actions logs later, so this folder preserves a copy inside the snapshot.\n\n"
        "Forensic value: these logs connect the committed snapshot back to the runner execution that produced it. "
        "The current job's final lines may be limited by what GitHub exposes while the job is still running."
    )
    write_readme(
        run_dir / "artifacts",
        "Artifacts",
        "Preserved website outputs: HTTP/WARC capture, WACZ package, static mirror, rendered mirror, screenshots, PDFs, "
        "SingleFile exports, robots/sitemap controls, and browser/network evidence.\n\n"
        "Forensic value: artifacts are the substantive preserved evidence. Reports and manifests explain them; "
        "hashes help verify them."
    )
    artifact_readmes = {
        "control": ("Control Files", "Robots and sitemap files captured from the public site. Forensic value: documents the public discovery sources and scope inputs used during collection."),
        "mirror": ("Static Mirror", "HTML captured through public HTTP requests with executable scripts disabled for offline review. Forensic value: preserves server-returned page markup and link structure."),
        "rendered-mirror": ("Rendered Mirror", "Browser-rendered HTML after page execution in the GitHub-hosted runner. Forensic value: documents visible/generated DOM content when static HTML is script-driven."),
        "screenshots": ("Screenshots", "Full-page PNG screenshots from the browser renderer. Forensic value: preserves visual page state as observed by the runner."),
        "pdf": ("PDFs", "PDF renderings from the browser renderer. Forensic value: provides printable visual records for selected pages."),
        "singlefile": ("SingleFile Exports", "Self-contained HTML exports when the SingleFile CLI succeeds. Forensic value: provides an additional replay/review format independent from the mirror."),
        "warc": ("WARC", "Compressed WARC created from public HTTP responses. Forensic value: preserves HTTP response payloads and headers in a standard web-archive format."),
        "wacz": ("WACZ", "WACZ package built from WARC output with an explicit page index derived from captured pages. Forensic value: provides a packaged web-archive format suitable for replay tooling when index validation succeeds."),
        "privacy": ("Browser Network And Cookie Evidence", "Browser-observed cookies, storage state, network events, headers, query values, console events, and page errors. Forensic value: records client-side behavior observed during public browsing from the runner."),
        "downloads": ("Downloads", "Public downloaded files discovered during capture, when any exist. Forensic value: preserves linked public documents or assets separately from page HTML."),
    }
    for dirname, (title, body) in artifact_readmes.items():
        write_readme(run_dir / "artifacts" / dirname, title, body)
    write_start_here(config, run_dir, str(summary.get("validation_status") or validation.get("status") or "unknown"))


def generate_report(config: CaptureConfig, run_dir: Path) -> Dict[str, object]:
    summary = summarize_run(run_dir)
    inventory = read_json(run_dir / "manifest" / "url-inventory.json", {}) or {}
    capture = read_json(run_dir / "manifest" / "capture-result.json", {}) or {}
    render = read_json(run_dir / "manifest" / "render-result.json", []) or []
    privacy = read_json(run_dir / "manifest" / "privacy-result.json", {}) or {}
    wacz = read_json(run_dir / "manifest" / "wacz-result.json", {}) or {}
    validation = read_json(run_dir / "manifest" / "validation.json", {}) or {}
    env = template_environment()
    context = {
        "config": config.to_dict(),
        "summary": summary,
        "inventory": inventory,
        "capture": capture,
        "render": render,
        "privacy": privacy,
        "wacz": wacz,
        "validation": validation,
        "anomaly_lines": anomaly_lines(validation),
        "generated_local": local_now(),
        "generated_utc": utc_now(),
    }
    write_snapshot_readmes(config, run_dir, context)
    write_tool_log_summary(run_dir)
    report_root = run_dir / "report"
    report_root.mkdir(parents=True, exist_ok=True)
    rendered_files = {}
    for name, output in [
        ("executive-summary.md.j2", "executive-summary.md"),
        ("methodology.md.j2", "methodology.md"),
        ("capture-report.md.j2", "capture-report.md"),
        ("integrity.md.j2", "integrity.md"),
        ("privacy-summary.md.j2", "privacy-summary.md"),
        ("limitations.md.j2", "limitations.md"),
        ("anomalies-retries.md.j2", "anomalies-retries.md"),
    ]:
        text = env.get_template(name).render(**context)
        path = report_root / output
        path.write_text(text, encoding="utf-8")
        rendered_files[output] = path.relative_to(run_dir).as_posix()
    combined = "\n\n".join((report_root / output).read_text(encoding="utf-8") for output in rendered_files)
    (report_root / "report.md").write_text(combined, encoding="utf-8")
    result = {"report_files": rendered_files, "combined_report": "report/report.md", "generated_local": local_now(), "generated_utc": utc_now()}
    write_json(run_dir / "manifest" / "report-result.json", result)
    return result
